name: oj

on: [push, pull_request]

jobs:
  oj:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper
      - name: Run tests
        run: |
          oj-verify run
