name: Unittest

on: [push, pull_request]

jobs:
  unittest:    
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: run unittest
        run: |
          mkdir build
          cd build
          cmake ../test -DCMAKE_BUILD_TYPE=Debug
          make
          ./unittest
        env:
          CXX: "clang++"
          GTEST_COLOR: "1"
